##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/peerless1230/onap_heat/onap.installation/cloudify_plugins/cloudify-cosmo/cloudify-fabric-plugin/archive/1.4.1.zip
        package_name: cloudify-fabric-plugin
        package_version: '1.4.1'
